spring.application.name=stripe-payment

spring.datasource.url=${URL_BANCO}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8080

stripe.webhookSecret=${STRIPE_WEBHOOK_SECRET}
stripe.secretKey=${STRIPE_SECRET_KEY}